$content = Get-Content -Path 'app\src\main\java\hcmute\edu\vn\mytasklist\MainActivity.java' -Raw
$content = $content -replace '        taskAdapter = new TaskAdapter\(TaskEntity -> \{', '        taskAdapter = new TaskAdapter(task -> {'
$content = $content -replace 'TaskEntity\.getId\(\)', 'task.getId()'
$content = $content -replace 'TaskEntity\.getTitle\(\)', 'task.getTitle()'
$content = $content -replace 'TaskEntity\.getCategory\(\)', 'task.getCategory()'
$content = $content -replace 'TaskEntity\.getPriority\(\)', 'task.getPriority()'
$content = $content -replace 'TaskEntity\.isCompleted\(\)', 'task.isCompleted()'
$content = $content -replace 'TaskEntity\.getRecurrence\(\)', 'task.getRecurrence()'
$content = $content -replace 'TaskEntity\.setDueDate\(selectedDateTime\.getTime\(\)\);', 'task.setDueDate(selectedDateTime.getTime().getTime());'
$content = $content -replace 'TaskEntity\.setTitle\(newTitle\);', 'task.setTitle(newTitle);'
$content = $content -replace 'TaskEntity\.setPriority\(pri\[0\]\);', 'task.setPriority(pri[0]);'
$content = $content -replace 'TaskEntity\.setCategory\(catNames', 'task.setCategory(catNames'
$content = $content -replace 'TaskEntity\.setRecurrence\(rs2\);', 'task.setRecurrence(rs2);'
$content = $content -replace 'taskViewModel\.update\(TaskEntity\);', 'taskViewModel.update(task);'
$content = $content -replace 'cloneRecurringTask\(TaskEntity\);', 'cloneRecurringTask(task);'
$content = $content -replace 'private void showEditTaskDialog\(TaskEntity TaskEntity\)', 'private void showEditTaskDialog(TaskEntity task)'
$content = $content -replace 'case HIGH:', 'case "HIGH":'
$content = $content -replace 'case MEDIUM:', 'case "MEDIUM":'
$content = $content -replace 'case LOW:', 'case "LOW":'
$content = $content -replace 'case NONE:', 'case "NONE":'
$content = $content -replace 'private List<TaskEntity> getFilteredTasks\(\) \{.*?\n    \}', 'private List<TaskEntity> getFilteredTasks() { List<TaskEntity> result = new ArrayList<>(); if (allTasks == null) return result; Date todayStart = getDayStart(new Date()); Calendar c = Calendar.getInstance(); c.add(Calendar.DAY_OF_YEAR, 1); Date tomorrowStart = getDayStart(c.getTime()); Calendar c7 = Calendar.getInstance(); c7.add(Calendar.DAY_OF_YEAR, 7); Date nextWeekStart = getDayStart(c7.getTime()); for (TaskEntity t : allTasks) { boolean include = false; if ("Today".equals(currentFilter)) { if (t.getDueDate() != null && getDayStart(new Date(t.getDueDate())).equals(todayStart)) include = true; } else if ("Next 7 Days".equals(currentFilter)) { if (t.getDueDate() != null && !getDayStart(new Date(t.getDueDate())).before(todayStart) && getDayStart(new Date(t.getDueDate())).before(nextWeekStart)) include = true; } else if ("Completed".equals(currentFilter)) { if (t.isCompleted()) include = true; } else { if (currentFilter.equals(t.getCategory())) include = true; } if (include) result.add(t); } return result; }'
Set-Content -Path 'app\src\main\java\hcmute\edu\vn\mytasklist\MainActivity.java' -Value $content
